### ISSUE TITLE
Can't log out

### ISSUE THREAD

**Issue by Buda9** [fmido88/moodle-auth_relogin#1]
This is awesome plugin. Finally a worthy "remember me" option that Moodle doesn't have. However, when all options are enabled, (Apply for login page, Permanent cookies and Use ip address), user simply can't log out.

Perhaps we should disable "Apply for login page" option?

**Comment by fmido88** [comment]
Greetings @Buda9
The problem I think is with using ip address option, tgus option will be removed in the next release, try disable it and check the functionality of the plugin.

**Comment by Buda9** [comment]
@fmido88 Thank you. I'll test it and notify you in a couple of days.

Btw. you have an email from me (from davorbudimir9 gmail)

**Comment by fmido88** [comment]
Hello @Buda9 
A new version with other fixes has been uploaded. You can try the new version.

And ok I'll check the mailbox and very sorry. these were a busy days.

**Comment by Buda9** [comment]
@fmido88 wow that's a lot of changes in the latest update, great job!

So far it's good, everything works as expected, I didn't notice any issues or that I'm being logged out. I'll notify you if I notice anything

**Comment by fmido88** [comment]
Thanks @Buda9

**Comment by Buda9** [comment]
Just to check in and say that far everything works perfectly

**Comment by fmido88** [comment]
Hi @Buda9
Glad to hear that, thank you.
